name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - 'src-tauri/src/**'
      - 'src-tauri/Cargo.toml'
      - 'src-tauri/tauri.config.json'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./src-tauri
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./src-tauri
      run: cargo test --verbose
